engine:
  task:
    dashboard:
      enabled: ${ENGINE_JOB_DASHBOARD_ENABLED:false}

custom:
  cors:
    allowed-origin-patterns:
      - "http://localhost:[*]"
      - '*'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count,X-${spring.application.name}-alert,X-${spring.application.name}-error,X-${spring.application.name}-params'
    allow-credentials: true
    max-age: 1800
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration: ${JWT_EXPIRATION_DURATION}

logging:
  structured:
    format:
      console: logstash
  level:
    stats: "OFF"
    perf: "OFF"