// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

export type GameConcept = {
    id?: string;
    name?: string;
};

export type GameDto = {
    id?: string;
    name?: string;
    owner?: string;
    domain?: string;
    actions?: Array<string>;
    rules?: Array<string>;
    tasks?: Array<GameTask>;
    concepts?: Array<GameConcept>;
    expiration?: number;
    terminated?: boolean;
};

export type GameTask = {
    name?: string;
    schedule?: TaskSchedule;
    executionActions?: Array<string>;
};

export type TaskSchedule = {
    cronExpression?: string;
    start?: string;
    period?: number;
    delay?: TimeInterval;
    frequency?: 'DAILY' | 'WEEKLY' | 'MONTHLY';
};

export type TimeInterval = {
    value?: number;
    unit?: 'MILLISEC' | 'SEC' | 'MINUTE' | 'HOUR' | 'DAY';
};

export type RuleDto = {
    id?: string;
    gameId: string;
    name: string;
    content: string;
};

export type ChallengeDto = {
    id?: string;
    name?: string;
    variables?: Array<string>;
    gameId?: string;
};

export type ActionDto = {
    name?: string;
};

export type BadgeCollectionDto = {
    id?: string;
    name?: string;
    hidden?: boolean;
    badges?: Array<string>;
};

export type ChallengeConceptDto = {
    name?: string;
    modelName?: string;
    state?: string;
    fields?: {
        [key: string]: unknown;
    };
    start?: string;
    end?: string;
};

export type PeriodDto = {
    identifier?: string;
    start?: number;
    end?: number;
    period?: number;
    capacity?: number;
};

export type PointConceptDto = {
    id?: string;
    name?: string;
    score?: number;
    periods?: {
        [key: string]: PeriodDto;
    };
};

export type SimulationRequestDto = {
    gameId: string;
    syntheticState: SyntheticStateDto;
    data?: {
        [key: string]: unknown;
    };
    executionMoment?: number;
    showDetailedChanges?: boolean;
};

export type SyntheticStateDto = {
    playerId?: string;
    actionIds?: Array<string>;
    pointConcepts?: Array<PointConceptDto>;
    badgeCollections?: Array<BadgeCollectionDto>;
    challenges?: Array<ChallengeConceptDto>;
    customData?: {
        [key: string]: unknown;
    };
};

export type ConceptChangeDto = {
    conceptType?: string;
    conceptName?: string;
    field?: string;
    before?: unknown;
    after?: unknown;
};

export type FiredRuleDto = {
    ruleName?: string;
    cause?: string;
    reads?: Array<string>;
    writes?: Array<string>;
    changes?: Array<ConceptChangeDto>;
};

export type PlayerStateDto = {
    playerId?: string;
    gameId?: string;
    pointConcepts?: Array<PointConceptDto>;
    badgeCollections?: Array<BadgeCollectionDto>;
    challenges?: Array<ChallengeConceptDto>;
};

export type SimulationResultDto = {
    initialState?: PlayerStateDto;
    finalState?: PlayerStateDto;
    firedRules?: Array<FiredRuleDto>;
    changes?: Array<ConceptChangeDto>;
};

export type ValidationMessageDto = {
    id?: number;
    text?: string;
    level?: 'ERROR' | 'WARNING' | 'INFO';
};

export type Config = {
    choices?: number;
    availableModels?: Array<string>;
    activeModels?: Array<string>;
};

export type LevelDto = {
    name?: string;
    pointConceptName?: string;
    thresholds?: Array<Threshold>;
};

export type Threshold = {
    name?: string;
    value?: number;
    index?: number;
    config?: Config;
};

export type ChallengeDisclosure = {
    startDate?: string;
    frequency?: TimeInterval;
};

export type ChallengeSettings = {
    disclosure?: ChallengeDisclosure;
};

export type GamePersistanceDto = {
    id?: string;
    name?: string;
    owner?: string;
    domain?: string;
    actions?: Array<string>;
    tasks?: Array<GenericObjectPersistence>;
    rules?: Array<string>;
    concepts?: Array<GenericObjectPersistence>;
    levels?: Array<Level>;
    expiration?: number;
    terminated?: boolean;
    settings?: Settings;
    notifyPCName?: Array<string>;
};

export type GenericObjectPersistence = {
    obj?: {
        [key: string]: unknown;
    };
    type?: string;
};

export type ImportGameDto = {
    game: GamePersistanceDto;
    challengeModels: Array<ChallengeDto>;
    rules: Array<RuleDto>;
};

export type Level = {
    name?: string;
    pointConceptName?: string;
    thresholds?: Array<Threshold>;
};

export type Settings = {
    statisticsConfig?: {
        [key: string]: string;
    };
    challengeSettings?: ChallengeSettings;
};

export type LoginRequestDto = {
    username: string;
    password: string;
};

export type ActivationLinkDto = {
    ruleName?: string;
    reactivity?: string;
};

export type RuleImpactDto = {
    ruleName?: string;
    reads?: Array<ConceptChangeDto>;
    writes?: Array<ConceptChangeDto>;
    activates?: Array<ActivationLinkDto>;
};

export type UserDto = {
    id?: string;
    username?: string;
    active?: boolean;
};

export type DeleteGameData = {
    body?: never;
    path: {
        gameId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}';
};

export type DeleteGameResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetGameData = {
    body?: never;
    path: {
        gameId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}';
};

export type GetGameResponses = {
    /**
     * OK
     */
    200: GameDto;
};

export type GetGameResponse = GetGameResponses[keyof GetGameResponses];

export type UpdateGameData = {
    body: GameDto;
    path: {
        gameId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}';
};

export type UpdateGameResponses = {
    /**
     * OK
     */
    200: GameDto;
};

export type UpdateGameResponse = UpdateGameResponses[keyof UpdateGameResponses];

export type DeleteRuleData = {
    body?: never;
    path: {
        gameId: string;
        ruleId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/rules/{ruleId}';
};

export type DeleteRuleResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetRuleData = {
    body?: never;
    path: {
        gameId: string;
        ruleId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/rules/{ruleId}';
};

export type GetRuleResponses = {
    /**
     * OK
     */
    200: RuleDto;
};

export type GetRuleResponse = GetRuleResponses[keyof GetRuleResponses];

export type EditRuleData = {
    body: RuleDto;
    path: {
        gameId: string;
        ruleId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/rules/{ruleId}';
};

export type EditRuleResponses = {
    /**
     * OK
     */
    200: RuleDto;
};

export type EditRuleResponse = EditRuleResponses[keyof EditRuleResponses];

export type DeleteGameChallengeData = {
    body?: never;
    path: {
        gameId: string;
        challengeId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/challenges/{challengeId}';
};

export type DeleteGameChallengeResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UpdateGameChallengeData = {
    body: ChallengeDto;
    path: {
        gameId: string;
        challengeId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/challenges/{challengeId}';
};

export type UpdateGameChallengeResponses = {
    /**
     * OK
     */
    200: ChallengeDto;
};

export type UpdateGameChallengeResponse = UpdateGameChallengeResponses[keyof UpdateGameChallengeResponses];

export type DeleteActionData = {
    body?: never;
    path: {
        gameId: string;
        actionId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/actions/{actionId}';
};

export type DeleteActionResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UpdateActionData = {
    body: ActionDto;
    path: {
        gameId: string;
        actionId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/actions/{actionId}';
};

export type UpdateActionResponses = {
    /**
     * OK
     */
    200: ActionDto;
};

export type UpdateActionResponse = UpdateActionResponses[keyof UpdateActionResponses];

export type SimulateData = {
    body: SimulationRequestDto;
    path?: never;
    query?: never;
    url: '/api/v1/simulate';
};

export type SimulateResponses = {
    /**
     * OK
     */
    200: SimulationResultDto;
};

export type SimulateResponse = SimulateResponses[keyof SimulateResponses];

export type GetGamesData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
        name?: string;
        domain?: string;
        terminated?: boolean;
    };
    url: '/api/v1/games';
};

export type GetGamesResponses = {
    /**
     * OK
     */
    200: Array<GameDto>;
};

export type GetGamesResponse = GetGamesResponses[keyof GetGamesResponses];

export type CreateGameData = {
    body: GameDto;
    path?: never;
    query?: never;
    url: '/api/v1/games';
};

export type CreateGameResponses = {
    /**
     * OK
     */
    200: GameDto;
};

export type CreateGameResponse = CreateGameResponses[keyof CreateGameResponses];

export type GetRulesData = {
    body?: never;
    path: {
        gameId: string;
    };
    query?: {
        id?: string;
        name?: string;
    };
    url: '/api/v1/games/{gameId}/rules';
};

export type GetRulesResponses = {
    /**
     * OK
     */
    200: Array<RuleDto>;
};

export type GetRulesResponse = GetRulesResponses[keyof GetRulesResponses];

export type AddRuleData = {
    body: RuleDto;
    path: {
        gameId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/rules';
};

export type AddRuleResponses = {
    /**
     * OK
     */
    200: RuleDto;
};

export type AddRuleResponse = AddRuleResponses[keyof AddRuleResponses];

export type ValidateRuleData = {
    body: RuleDto;
    path: {
        gameId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/rules/validate';
};

export type ValidateRuleResponses = {
    /**
     * OK
     */
    200: Array<ValidationMessageDto>;
};

export type ValidateRuleResponse = ValidateRuleResponses[keyof ValidateRuleResponses];

export type GetPointsData = {
    body?: never;
    path: {
        gameId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/point-concepts';
};

export type GetPointsResponses = {
    /**
     * OK
     */
    200: Array<PointConceptDto>;
};

export type GetPointsResponse = GetPointsResponses[keyof GetPointsResponses];

export type AddPointData = {
    body: PointConceptDto;
    path: {
        gameId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/point-concepts';
};

export type AddPointResponses = {
    /**
     * OK
     */
    200: PointConceptDto;
};

export type AddPointResponse = AddPointResponses[keyof AddPointResponses];

export type GetLevelsData = {
    body?: never;
    path: {
        gameId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/levels';
};

export type GetLevelsResponses = {
    /**
     * OK
     */
    200: Array<LevelDto>;
};

export type GetLevelsResponse = GetLevelsResponses[keyof GetLevelsResponses];

export type UpsertLevelData = {
    body: LevelDto;
    path: {
        gameId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/levels';
};

export type UpsertLevelResponses = {
    /**
     * OK
     */
    200: LevelDto;
};

export type UpsertLevelResponse = UpsertLevelResponses[keyof UpsertLevelResponses];

export type GetGameChallengesData = {
    body?: never;
    path: {
        gameId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/challenges';
};

export type GetGameChallengesResponses = {
    /**
     * OK
     */
    200: Array<ChallengeDto>;
};

export type GetGameChallengesResponse = GetGameChallengesResponses[keyof GetGameChallengesResponses];

export type AddGameChallengeData = {
    body: ChallengeDto;
    path: {
        gameId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/challenges';
};

export type AddGameChallengeResponses = {
    /**
     * OK
     */
    200: ChallengeDto;
};

export type AddGameChallengeResponse = AddGameChallengeResponses[keyof AddGameChallengeResponses];

export type GetBadgeCollectionsData = {
    body?: never;
    path: {
        gameId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/badges';
};

export type GetBadgeCollectionsResponses = {
    /**
     * OK
     */
    200: Array<BadgeCollectionDto>;
};

export type GetBadgeCollectionsResponse = GetBadgeCollectionsResponses[keyof GetBadgeCollectionsResponses];

export type AddBadgeCollectionData = {
    body: BadgeCollectionDto;
    path: {
        gameId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/badges';
};

export type AddBadgeCollectionResponses = {
    /**
     * OK
     */
    200: BadgeCollectionDto;
};

export type AddBadgeCollectionResponse = AddBadgeCollectionResponses[keyof AddBadgeCollectionResponses];

export type GetActionsData = {
    body?: never;
    path: {
        gameId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/actions';
};

export type GetActionsResponses = {
    /**
     * OK
     */
    200: Array<ActionDto>;
};

export type GetActionsResponse = GetActionsResponses[keyof GetActionsResponses];

export type AddActionData = {
    body: ActionDto;
    path: {
        gameId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/actions';
};

export type AddActionResponses = {
    /**
     * OK
     */
    200: ActionDto;
};

export type AddActionResponse = AddActionResponses[keyof AddActionResponses];

export type ImportGamesData = {
    body: Array<ImportGameDto>;
    path?: never;
    query?: never;
    url: '/api/v1/games/import';
};

export type ImportGamesResponses = {
    /**
     * OK
     */
    200: Array<GamePersistanceDto>;
};

export type ImportGamesResponse = ImportGamesResponses[keyof ImportGamesResponses];

export type LoginData = {
    body: LoginRequestDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth';
};

export type LoginResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type DeletePointData = {
    body?: never;
    path: {
        gameId: string;
        pointId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/point-concepts/{pointId}';
};

export type DeletePointResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetPointData = {
    body?: never;
    path: {
        gameId: string;
        pointId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/point-concepts/{pointId}';
};

export type GetPointResponses = {
    /**
     * OK
     */
    200: PointConceptDto;
};

export type GetPointResponse = GetPointResponses[keyof GetPointResponses];

export type GetLevelData = {
    body?: never;
    path: {
        gameId: string;
        levelId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/levels/{levelId}';
};

export type GetLevelResponses = {
    /**
     * OK
     */
    200: LevelDto;
};

export type GetLevelResponse = GetLevelResponses[keyof GetLevelResponses];

export type AnalyzeGameData = {
    body?: never;
    path: {
        gameId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/impact';
};

export type AnalyzeGameResponses = {
    /**
     * OK
     */
    200: Array<RuleImpactDto>;
};

export type AnalyzeGameResponse = AnalyzeGameResponses[keyof AnalyzeGameResponses];

export type DeleteBadgeCollectionData = {
    body?: never;
    path: {
        gameId: string;
        collectionId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/badges/{collectionId}';
};

export type DeleteBadgeCollectionResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetBadgeCollectionData = {
    body?: never;
    path: {
        gameId: string;
        collectionId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/badges/{collectionId}';
};

export type GetBadgeCollectionResponses = {
    /**
     * OK
     */
    200: BadgeCollectionDto;
};

export type GetBadgeCollectionResponse = GetBadgeCollectionResponses[keyof GetBadgeCollectionResponses];

export type GetAuthenticatedUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/user';
};

export type GetAuthenticatedUserResponses = {
    /**
     * OK
     */
    200: UserDto;
};

export type GetAuthenticatedUserResponse = GetAuthenticatedUserResponses[keyof GetAuthenticatedUserResponses];

export type UpsertLevel1Data = {
    body?: never;
    path: {
        gameId: string;
        lvlName: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/levels/{lvlName}';
};

export type UpsertLevel1Responses = {
    /**
     * OK
     */
    200: LevelDto;
};

export type UpsertLevel1Response = UpsertLevel1Responses[keyof UpsertLevel1Responses];
