// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

export type GameConcept = {
    id?: string;
    name?: string;
};

export type GameDto = {
    id?: string;
    name?: string;
    owner?: string;
    domain?: string;
    actions?: Array<string>;
    rules?: Array<string>;
    tasks?: Array<GameTask>;
    concepts?: Array<GameConcept>;
    expiration?: number;
    terminated?: boolean;
};

export type GameTask = {
    name?: string;
    schedule?: TaskSchedule;
    executionActions?: Array<string>;
};

export type TaskSchedule = {
    cronExpression?: string;
    start?: string;
    period?: number;
    delay?: TimeInterval;
    frequency?: 'DAILY' | 'WEEKLY' | 'MONTHLY';
};

export type TimeInterval = {
    value?: number;
    unit?: 'MILLISEC' | 'SEC' | 'MINUTE' | 'HOUR' | 'DAY';
};

export type TeamDto = {
    id?: string;
    gameId?: string;
    name?: string;
    members?: Array<string>;
};

export type BadgeCollectionDto = {
    id?: string;
    name?: string;
    hidden?: boolean;
    badges?: Array<string>;
};

export type ChallengeConceptDto = {
    name?: string;
    modelName?: string;
    state?: string;
    fields?: {
        [key: string]: unknown;
    };
    start?: string;
    end?: string;
};

export type PeriodDto = {
    identifier?: string;
    start?: number;
    end?: number;
    period?: number;
    capacity?: number;
};

export type PointConceptDto = {
    id?: string;
    name: string;
    score?: number;
    periods?: {
        [key: string]: PeriodDto;
    };
};

export type SimulationScenarioDto = {
    id?: string;
    gameId?: string;
    name?: string;
    syntheticState?: SyntheticStateDto;
    expectedOutput?: SyntheticStateDto;
};

export type SyntheticStateDto = {
    playerId?: string;
    actionIds?: Array<string>;
    pointConcepts?: Array<PointConceptDto>;
    badgeCollections?: Array<BadgeCollectionDto>;
    challenges?: Array<ChallengeConceptDto>;
    customData?: {
        [key: string]: unknown;
    };
};

export type RuleDto = {
    id?: string;
    gameId: string;
    name: string;
    content: string;
};

export type ChallengeDto = {
    id?: string;
    name?: string;
    variables?: Array<string>;
    gameId?: string;
};

export type ActionDto = {
    name?: string;
};

export type ValidationMessageDto = {
    id?: number;
    text?: string;
    level?: 'ERROR' | 'WARNING' | 'INFO';
};

export type ChallengeChoice = {
    modelName?: string;
    state?: 'AVAILABLE' | 'ACTIVE';
};

export type Inventory = {
    challengeChoices?: Array<ChallengeChoice>;
    challengeActivationActions?: number;
};

export type PlayerDto = {
    playerId?: string;
    gameId?: string;
    levels?: Array<PlayerLevel>;
    state?: Array<GameConcept>;
    customData?: {
        data?: {
            [key: string]: unknown;
        };
        empty?: boolean;
        [key: string]: unknown;
    };
    inventory?: Inventory;
};

export type PlayerLevel = {
    levelName?: string;
    levelValue?: string;
    levelIndex?: number;
    pointConcept?: string;
    startLevelScore?: number;
    endLevelScore?: number;
    toNextLevel?: number;
};

export type LevelDto = {
    name?: string;
    pointConceptName?: string;
    thresholds?: Array<ThresholdDto>;
};

export type ThresholdConfigDto = {
    choices?: number;
    availableModels?: Array<string>;
    activeModels?: Array<string>;
};

export type ThresholdDto = {
    name?: string;
    value?: number;
    index?: number;
    config?: ThresholdConfigDto;
};

export type ChallengeDisclosure = {
    startDate?: string;
    frequency?: TimeInterval;
};

export type ChallengeSettings = {
    disclosure?: ChallengeDisclosure;
};

export type Config = {
    choices?: number;
    availableModels?: Array<string>;
    activeModels?: Array<string>;
};

export type GamePersistanceDto = {
    id?: string;
    name?: string;
    owner?: string;
    domain?: string;
    actions?: Array<string>;
    tasks?: Array<GenericObjectPersistence>;
    rules?: Array<string>;
    concepts?: Array<GenericObjectPersistence>;
    levels?: Array<Level>;
    expiration?: number;
    terminated?: boolean;
    settings?: Settings;
    notifyPCName?: Array<string>;
};

export type GenericObjectPersistence = {
    obj?: {
        [key: string]: unknown;
    };
    type?: string;
};

export type ImportGameDto = {
    game: GamePersistanceDto;
    challengeModels: Array<ChallengeDto>;
    rules: Array<RuleDto>;
};

export type Level = {
    name?: string;
    pointConceptName?: string;
    thresholds?: Array<Threshold>;
};

export type Settings = {
    statisticsConfig?: {
        [key: string]: string;
    };
    challengeSettings?: ChallengeSettings;
};

export type Threshold = {
    name?: string;
    value?: number;
    index?: number;
    config?: Config;
};

export type ExecutionDto = {
    gameId: string;
    actionId: string;
    playerId: string;
    data: {
        [key: string]: unknown;
    };
    customData?: Array<unknown>;
    executionMoment?: string;
};

export type PlayerState = {
    playerId?: string;
    gameId?: string;
    levels?: Array<PlayerLevel>;
    state?: Array<GameConcept>;
    customData?: {
        data?: {
            [key: string]: unknown;
        };
        empty?: boolean;
        [key: string]: unknown;
    };
    inventory?: Inventory;
};

export type SimulationRequestDto = {
    gameId: string;
    syntheticState: SyntheticStateDto;
    data?: {
        [key: string]: unknown;
    };
    executionMoment?: number;
    showDetailedChanges?: boolean;
};

export type ConceptChangeDto = {
    conceptType?: string;
    conceptName?: string;
    field?: string;
    before?: unknown;
    after?: unknown;
};

export type FiredRuleDto = {
    ruleName?: string;
    cause?: string;
    reads?: Array<string>;
    writes?: Array<string>;
    changes?: Array<ConceptChangeDto>;
};

export type PlayerStateDto = {
    playerId?: string;
    gameId?: string;
    pointConcepts?: Array<PointConceptDto>;
    badgeCollections?: Array<BadgeCollectionDto>;
    challenges?: Array<ChallengeConceptDto>;
};

export type SimulationResultDto = {
    initialState?: PlayerStateDto;
    finalState?: PlayerStateDto;
    firedRules?: Array<FiredRuleDto>;
    changes?: Array<ConceptChangeDto>;
};

export type LoginRequestDto = {
    username: string;
    password: string;
};

export type UserDto = {
    id?: string;
    username?: string;
    active?: boolean;
};

export type PagePlayerDto = {
    totalPages?: number;
    totalElements?: number;
    size?: number;
    content?: Array<PlayerDto>;
    number?: number;
    sort?: SortObject;
    first?: boolean;
    last?: boolean;
    numberOfElements?: number;
    pageable?: PageableObject;
    empty?: boolean;
};

export type PageableObject = {
    offset?: number;
    sort?: SortObject;
    paged?: boolean;
    pageNumber?: number;
    pageSize?: number;
    unpaged?: boolean;
};

export type SortObject = {
    empty?: boolean;
    unsorted?: boolean;
    sorted?: boolean;
};

export type NotificationDto = {
    type?: string;
    gameId?: string;
    playerId?: string;
    timestamp?: number;
    badge?: string;
    collectionName?: string;
    challengeName?: string;
    model?: string;
    pointConcept?: string;
    guestId?: string;
    proposerId?: string;
    start?: number;
    end?: number;
    classificationName?: string;
    classificationPosition?: number;
    actionId?: string;
    dataPayLoad?: {
        [key: string]: unknown;
    };
    scoreMap?: {
        [key: string]: number;
    };
    deltaMap?: {
        [key: string]: number;
    };
    levelName?: string;
    levelType?: string;
    levelIndex?: number;
    key?: string;
    data?: {
        [key: string]: unknown;
    };
};

export type ActivationLinkDto = {
    ruleName?: string;
    reactivity?: string;
};

export type RuleImpactDto = {
    ruleName?: string;
    reads?: Array<ConceptChangeDto>;
    writes?: Array<ConceptChangeDto>;
    activates?: Array<ActivationLinkDto>;
};

export type DeleteGameData = {
    body?: never;
    path: {
        gameId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}';
};

export type DeleteGameResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetGameData = {
    body?: never;
    path: {
        gameId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}';
};

export type GetGameResponses = {
    /**
     * OK
     */
    200: GameDto;
};

export type GetGameResponse = GetGameResponses[keyof GetGameResponses];

export type UpdateGameData = {
    body: GameDto;
    path: {
        gameId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}';
};

export type UpdateGameResponses = {
    /**
     * OK
     */
    200: GameDto;
};

export type UpdateGameResponse = UpdateGameResponses[keyof UpdateGameResponses];

export type DeleteTeamData = {
    body?: never;
    path: {
        gameId: string;
        teamId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/teams/{teamId}';
};

export type DeleteTeamResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetTeamData = {
    body?: never;
    path: {
        gameId: string;
        teamId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/teams/{teamId}';
};

export type GetTeamResponses = {
    /**
     * OK
     */
    200: TeamDto;
};

export type GetTeamResponse = GetTeamResponses[keyof GetTeamResponses];

export type UpdateTeamData = {
    body: TeamDto;
    path: {
        gameId: string;
        teamId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/teams/{teamId}';
};

export type UpdateTeamResponses = {
    /**
     * OK
     */
    200: TeamDto;
};

export type UpdateTeamResponse = UpdateTeamResponses[keyof UpdateTeamResponses];

export type DeleteScenarioData = {
    body?: never;
    path: {
        gameId: string;
        scenarioId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/scenarios/{scenarioId}';
};

export type DeleteScenarioResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetScenarioData = {
    body?: never;
    path: {
        gameId: string;
        scenarioId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/scenarios/{scenarioId}';
};

export type GetScenarioResponses = {
    /**
     * OK
     */
    200: SimulationScenarioDto;
};

export type GetScenarioResponse = GetScenarioResponses[keyof GetScenarioResponses];

export type UpdateScenarioData = {
    body: SimulationScenarioDto;
    path: {
        gameId: string;
        scenarioId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/scenarios/{scenarioId}';
};

export type UpdateScenarioResponses = {
    /**
     * OK
     */
    200: SimulationScenarioDto;
};

export type UpdateScenarioResponse = UpdateScenarioResponses[keyof UpdateScenarioResponses];

export type DeleteRuleData = {
    body?: never;
    path: {
        gameId: string;
        ruleId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/rules/{ruleId}';
};

export type DeleteRuleResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetRuleData = {
    body?: never;
    path: {
        gameId: string;
        ruleId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/rules/{ruleId}';
};

export type GetRuleResponses = {
    /**
     * OK
     */
    200: RuleDto;
};

export type GetRuleResponse = GetRuleResponses[keyof GetRuleResponses];

export type EditRuleData = {
    body: RuleDto;
    path: {
        gameId: string;
        ruleId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/rules/{ruleId}';
};

export type EditRuleResponses = {
    /**
     * OK
     */
    200: RuleDto;
};

export type EditRuleResponse = EditRuleResponses[keyof EditRuleResponses];

export type DeleteGameChallengeData = {
    body?: never;
    path: {
        gameId: string;
        challengeId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/challenges/{challengeId}';
};

export type DeleteGameChallengeResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UpdateGameChallengeData = {
    body: ChallengeDto;
    path: {
        gameId: string;
        challengeId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/challenges/{challengeId}';
};

export type UpdateGameChallengeResponses = {
    /**
     * OK
     */
    200: ChallengeDto;
};

export type UpdateGameChallengeResponse = UpdateGameChallengeResponses[keyof UpdateGameChallengeResponses];

export type DeleteBadgeCollectionData = {
    body?: never;
    path: {
        gameId: string;
        collectionId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/badges/{collectionId}';
};

export type DeleteBadgeCollectionResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetBadgeCollectionData = {
    body?: never;
    path: {
        gameId: string;
        collectionId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/badges/{collectionId}';
};

export type GetBadgeCollectionResponses = {
    /**
     * OK
     */
    200: BadgeCollectionDto;
};

export type GetBadgeCollectionResponse = GetBadgeCollectionResponses[keyof GetBadgeCollectionResponses];

export type UpdateBadgeCollectionData = {
    body: BadgeCollectionDto;
    path: {
        gameId: string;
        collectionId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/badges/{collectionId}';
};

export type UpdateBadgeCollectionResponses = {
    /**
     * OK
     */
    200: BadgeCollectionDto;
};

export type UpdateBadgeCollectionResponse = UpdateBadgeCollectionResponses[keyof UpdateBadgeCollectionResponses];

export type DeleteActionData = {
    body?: never;
    path: {
        gameId: string;
        actionId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/actions/{actionId}';
};

export type DeleteActionResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UpdateActionData = {
    body: ActionDto;
    path: {
        gameId: string;
        actionId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/actions/{actionId}';
};

export type UpdateActionResponses = {
    /**
     * OK
     */
    200: ActionDto;
};

export type UpdateActionResponse = UpdateActionResponses[keyof UpdateActionResponses];

export type GetGamesData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
        name?: string;
        domain?: string;
        terminated?: boolean;
    };
    url: '/api/v1/games';
};

export type GetGamesResponses = {
    /**
     * OK
     */
    200: Array<GameDto>;
};

export type GetGamesResponse = GetGamesResponses[keyof GetGamesResponses];

export type CreateGameData = {
    body: GameDto;
    path?: never;
    query?: never;
    url: '/api/v1/games';
};

export type CreateGameResponses = {
    /**
     * OK
     */
    200: GameDto;
};

export type CreateGameResponse = CreateGameResponses[keyof CreateGameResponses];

export type GetTeamsData = {
    body?: never;
    path: {
        gameId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/teams';
};

export type GetTeamsResponses = {
    /**
     * OK
     */
    200: Array<TeamDto>;
};

export type GetTeamsResponse = GetTeamsResponses[keyof GetTeamsResponses];

export type CreateTeamData = {
    body: TeamDto;
    path: {
        gameId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/teams';
};

export type CreateTeamResponses = {
    /**
     * OK
     */
    200: TeamDto;
};

export type CreateTeamResponse = CreateTeamResponses[keyof CreateTeamResponses];

export type GetScenariosData = {
    body?: never;
    path: {
        gameId: string;
    };
    query?: {
        id?: string;
        name?: string;
    };
    url: '/api/v1/games/{gameId}/scenarios';
};

export type GetScenariosResponses = {
    /**
     * OK
     */
    200: Array<SimulationScenarioDto>;
};

export type GetScenariosResponse = GetScenariosResponses[keyof GetScenariosResponses];

export type CreateScenarioData = {
    body: SimulationScenarioDto;
    path: {
        gameId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/scenarios';
};

export type CreateScenarioResponses = {
    /**
     * OK
     */
    200: SimulationScenarioDto;
};

export type CreateScenarioResponse = CreateScenarioResponses[keyof CreateScenarioResponses];

export type GetRulesData = {
    body?: never;
    path: {
        gameId: string;
    };
    query?: {
        id?: string;
        name?: string;
    };
    url: '/api/v1/games/{gameId}/rules';
};

export type GetRulesResponses = {
    /**
     * OK
     */
    200: Array<RuleDto>;
};

export type GetRulesResponse = GetRulesResponses[keyof GetRulesResponses];

export type AddRuleData = {
    body: RuleDto;
    path: {
        gameId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/rules';
};

export type AddRuleResponses = {
    /**
     * OK
     */
    200: RuleDto;
};

export type AddRuleResponse = AddRuleResponses[keyof AddRuleResponses];

export type ValidateRuleData = {
    body: RuleDto;
    path: {
        gameId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/rules/validate';
};

export type ValidateRuleResponses = {
    /**
     * OK
     */
    200: Array<ValidationMessageDto>;
};

export type ValidateRuleResponse = ValidateRuleResponses[keyof ValidateRuleResponses];

export type GetPointsData = {
    body?: never;
    path: {
        gameId: string;
    };
    query?: {
        id?: string;
        name?: string;
    };
    url: '/api/v1/games/{gameId}/point-concepts';
};

export type GetPointsResponses = {
    /**
     * OK
     */
    200: Array<PointConceptDto>;
};

export type GetPointsResponse = GetPointsResponses[keyof GetPointsResponses];

export type AddPointData = {
    body: PointConceptDto;
    path: {
        gameId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/point-concepts';
};

export type AddPointResponses = {
    /**
     * OK
     */
    200: PointConceptDto;
};

export type AddPointResponse = AddPointResponses[keyof AddPointResponses];

export type GetPlayersData = {
    body?: never;
    path: {
        gameId: string;
    };
    query?: {
        /**
         * Zero-based page index (0..N)
         */
        page?: number;
        /**
         * The size of the page to be returned
         */
        size?: number;
        /**
         * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         */
        sort?: Array<string>;
        playerId?: string;
    };
    url: '/api/v1/games/{gameId}/players';
};

export type GetPlayersResponses = {
    /**
     * OK
     */
    200: PagePlayerDto;
};

export type GetPlayersResponse = GetPlayersResponses[keyof GetPlayersResponses];

export type AddPlayerData = {
    body: PlayerDto;
    path: {
        gameId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/players';
};

export type AddPlayerResponses = {
    /**
     * OK
     */
    200: PlayerDto;
};

export type AddPlayerResponse = AddPlayerResponses[keyof AddPlayerResponses];

export type GetLevelsData = {
    body?: never;
    path: {
        gameId: string;
    };
    query?: {
        name?: string;
        pointConceptName?: string;
    };
    url: '/api/v1/games/{gameId}/levels';
};

export type GetLevelsResponses = {
    /**
     * OK
     */
    200: Array<LevelDto>;
};

export type GetLevelsResponse = GetLevelsResponses[keyof GetLevelsResponses];

export type UpsertLevelData = {
    body: LevelDto;
    path: {
        gameId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/levels';
};

export type UpsertLevelResponses = {
    /**
     * OK
     */
    200: LevelDto;
};

export type UpsertLevelResponse = UpsertLevelResponses[keyof UpsertLevelResponses];

export type GetGameChallengesData = {
    body?: never;
    path: {
        gameId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/challenges';
};

export type GetGameChallengesResponses = {
    /**
     * OK
     */
    200: Array<ChallengeDto>;
};

export type GetGameChallengesResponse = GetGameChallengesResponses[keyof GetGameChallengesResponses];

export type AddGameChallengeData = {
    body: ChallengeDto;
    path: {
        gameId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/challenges';
};

export type AddGameChallengeResponses = {
    /**
     * OK
     */
    200: ChallengeDto;
};

export type AddGameChallengeResponse = AddGameChallengeResponses[keyof AddGameChallengeResponses];

export type GetBadgeCollectionsData = {
    body?: never;
    path: {
        gameId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/badges';
};

export type GetBadgeCollectionsResponses = {
    /**
     * OK
     */
    200: Array<BadgeCollectionDto>;
};

export type GetBadgeCollectionsResponse = GetBadgeCollectionsResponses[keyof GetBadgeCollectionsResponses];

export type AddBadgeCollectionData = {
    body: BadgeCollectionDto;
    path: {
        gameId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/badges';
};

export type AddBadgeCollectionResponses = {
    /**
     * OK
     */
    200: BadgeCollectionDto;
};

export type AddBadgeCollectionResponse = AddBadgeCollectionResponses[keyof AddBadgeCollectionResponses];

export type GetActionsData = {
    body?: never;
    path: {
        gameId: string;
    };
    query?: {
        name?: string;
    };
    url: '/api/v1/games/{gameId}/actions';
};

export type GetActionsResponses = {
    /**
     * OK
     */
    200: Array<ActionDto>;
};

export type GetActionsResponse = GetActionsResponses[keyof GetActionsResponses];

export type AddActionData = {
    body: ActionDto;
    path: {
        gameId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/actions';
};

export type AddActionResponses = {
    /**
     * OK
     */
    200: ActionDto;
};

export type AddActionResponse = AddActionResponses[keyof AddActionResponses];

export type ImportGamesData = {
    body: Array<ImportGameDto>;
    path?: never;
    query?: never;
    url: '/api/v1/games/import';
};

export type ImportGamesResponses = {
    /**
     * OK
     */
    200: Array<GamePersistanceDto>;
};

export type ImportGamesResponse = ImportGamesResponses[keyof ImportGamesResponses];

export type ExecuteGameData = {
    body: ExecutionDto;
    path?: never;
    query?: never;
    url: '/api/v1/executions';
};

export type ExecuteGameResponses = {
    /**
     * OK
     */
    200: PlayerState;
};

export type ExecuteGameResponse = ExecuteGameResponses[keyof ExecuteGameResponses];

export type SimulateData = {
    body: SimulationRequestDto;
    path?: never;
    query?: never;
    url: '/api/v1/executions/simulations';
};

export type SimulateResponses = {
    /**
     * OK
     */
    200: SimulationResultDto;
};

export type SimulateResponse = SimulateResponses[keyof SimulateResponses];

export type LoginData = {
    body: LoginRequestDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth';
};

export type LoginResponses = {
    /**
     * OK
     */
    200: UserDto;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type LogoutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeletePointData = {
    body?: never;
    path: {
        gameId: string;
        pointId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/point-concepts/{pointId}';
};

export type DeletePointResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetPointData = {
    body?: never;
    path: {
        gameId: string;
        pointId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/point-concepts/{pointId}';
};

export type GetPointResponses = {
    /**
     * OK
     */
    200: PointConceptDto;
};

export type GetPointResponse = GetPointResponses[keyof GetPointResponses];

export type UpdatePointData = {
    body: PointConceptDto;
    path: {
        gameId: string;
        pointId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/point-concepts/{pointId}';
};

export type UpdatePointResponses = {
    /**
     * OK
     */
    200: PointConceptDto;
};

export type UpdatePointResponse = UpdatePointResponses[keyof UpdatePointResponses];

export type DeletePlayerData = {
    body?: never;
    path: {
        gameId: string;
        playerId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/players/{playerId}';
};

export type DeletePlayerResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetPlayerData = {
    body?: never;
    path: {
        gameId: string;
        playerId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/players/{playerId}';
};

export type GetPlayerResponses = {
    /**
     * OK
     */
    200: PlayerStateDto;
};

export type GetPlayerResponse = GetPlayerResponses[keyof GetPlayerResponses];

export type GetNotificationsData = {
    body?: never;
    path: {
        gameId: string;
    };
    query?: {
        playerId?: string;
        type?: string;
        fromTs?: number;
        toTs?: number;
        /**
         * Zero-based page index (0..N)
         */
        page?: number;
        /**
         * The size of the page to be returned
         */
        size?: number;
        /**
         * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         */
        sort?: Array<string>;
    };
    url: '/api/v1/games/{gameId}/notifications';
};

export type GetNotificationsResponses = {
    /**
     * OK
     */
    200: Array<NotificationDto>;
};

export type GetNotificationsResponse = GetNotificationsResponses[keyof GetNotificationsResponses];

export type GetLevelData = {
    body?: never;
    path: {
        gameId: string;
        levelId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/levels/{levelId}';
};

export type GetLevelResponses = {
    /**
     * OK
     */
    200: LevelDto;
};

export type GetLevelResponse = GetLevelResponses[keyof GetLevelResponses];

export type AnalyzeGameData = {
    body?: never;
    path: {
        gameId: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/impact';
};

export type AnalyzeGameResponses = {
    /**
     * OK
     */
    200: Array<RuleImpactDto>;
};

export type AnalyzeGameResponse = AnalyzeGameResponses[keyof AnalyzeGameResponses];

export type GetAuthenticatedUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/user';
};

export type GetAuthenticatedUserResponses = {
    /**
     * OK
     */
    200: UserDto;
};

export type GetAuthenticatedUserResponse = GetAuthenticatedUserResponses[keyof GetAuthenticatedUserResponses];

export type UpsertLevel1Data = {
    body?: never;
    path: {
        gameId: string;
        lvlName: string;
    };
    query?: never;
    url: '/api/v1/games/{gameId}/levels/{lvlName}';
};

export type UpsertLevel1Responses = {
    /**
     * OK
     */
    200: LevelDto;
};

export type UpsertLevel1Response = UpsertLevel1Responses[keyof UpsertLevel1Responses];
