package eu.trentorise.game.model
import eu.trentorise.game.core.Utility;
import eu.trentorise.game.notification.MessageNotification;
import java.lang.Math;
import java.util.Map;

global Utility utils;
global Double green_transit_points;
global Double green_boat_points;
global Double park_and_ride_points;
global Double driver_first_passenger_bonus;
global Double driver_other_passenger_bonus;
global Double passenger_bonus;
global Double transit_daily_max;
global Double carpooling_daily_max;
global Double boat_daily_max;
global Double carpooling_min_km;
global Double boat_min_km;
global java.util.ArrayList parkings;

function double getModePoint(String mode) {
        switch (mode) {
            case 'Walk':
                return 25.0;
            case 'Bike':
                return 10.0;
            case 'Bus':
                return 5.0;
            case 'Train':
                return 2.5;
            default:
                return 0.0;
        }
}

function double getModeLimit(String mode) {
        switch (mode) {
            case 'Walk':
                return 2.0;
            case 'Bike':
                return 5.0;
            case 'Bus':
                return 10.0;
            case 'Train':
                return 20.0;
            default:
                return 0.0;
        }
}

function double getScore(String mode, double distance) {
        double point = getModePoint(mode);
        double limit = getModeLimit(mode);
        double score = 0.0;
        int index = 0;
        while (index < 10) {
            score += Math.min(distance, limit) * point;
            distance -= limit;
            point /= 2;
            if (distance < 0) {
                break;
            }
            index++;
        }
        return score;
}

function double tripScore(double modeDaily, double tripDistance, String mode) {
        double beforeTripDistance = modeDaily - tripDistance;
        double oldModeDailyScore = Math.rint(getScore(mode, beforeTripDistance));
        double newModeDailyScore = Math.rint(getScore(mode, modeDaily));
        double gainedScore = newModeDailyScore - oldModeDailyScore;
        return gainedScore;
}

rule "all modes - update green points"
    salience -500
    no-loop false
    lock-on-active false
    when
        Action(id == "save_itinerary")
        $inputData : InputData()
        Game($gameId : id)
        Player($playerId : id)
        $pc : PointConcept(name == "green leaves")
        $walkKm : PointConcept(name == "Walk_Km")
        $bikeKm : PointConcept(name == "Bike_Km")
        $busKm : PointConcept(name == "Bus_Km")
        $trainKm : PointConcept(name == "Train_Km")
        $transitTrips : PointConcept(name == "Transit_Trips")
        $carpoolingTrips : PointConcept(name == "Carpooling_Trips")
        $boatTrips : PointConcept(name == "Boat_Trips")
    then
        utils.log("all modes - update green points");
        Map data = $inputData.getData();
        Object travelId = data.get("travelId");
        Double walk = (Double) data.get("walkDistance");
        Double bike = (Double) data.get("bikeDistance");
        Double bus = (Double) data.get("busDistance");
        Double cable = (Double) data.get("transitDistance");
        Double train = (Double) data.get("trainDistance");
        String park = (String) data.get("park");
        Double boat = (Double) data.get("boatDistance");
        Double carpooling = (Double) data.get("carpoolingDistance");
        Boolean isDriver = (Boolean) data.get("driverTrip");
        Boolean firstPair = (Boolean) data.get("firstPair");

        double score = 0.0;
        if (walk != null) {
            utils.log("rule \'all modes - update green points\': counting Walking Km green points");
            double modeDaily = $walkKm.getPeriodCurrentScore("daily");
            double gainedScore = tripScore(modeDaily, (double) walk, "Walk");
            utils.log("daily Km: " + modeDaily);
            score += gainedScore;
        }
        if (bike != null) {
            utils.log("rule \'all modes - update green points\': counting Bike Km green points");
            double modeDaily = $bikeKm.getPeriodCurrentScore("daily");
            double gainedScore = tripScore(modeDaily, (double) bike, "Bike");
            utils.log("daily Km: " + modeDaily);
            score += gainedScore;
        }
        if (park != null && parkings.contains(park)) {
            utils.log("rule \'all modes - update green points\': counting P&R green points");
            score = score + park_and_ride_points;
        }
        if (cable != null) {
            Double transitDaily = $transitTrips.getPeriodCurrentScore("daily");
            utils.log("rule \'all modes - update green points\': counting Cable-Transit green points");
            if (transitDaily < transit_daily_max) {
                score = score + green_transit_points;
            } else {
                utils.log("rule \'all modes - update green points\': Reached daily limit for transit trips (cable)");
            }
        }
        if (boat != null && boat >= boat_min_km) {
            utils.log("rule \'all modes - update green points\': counting Boat green points");
            Double boatDaily = $boatTrips.getPeriodCurrentScore("daily");
            if (boatDaily <= boat_daily_max) {
                score = score + green_boat_points;
            } else {
                utils.log("rule \'all modes - update green points\': Reached daily limit for boat trips");
            }
        }
        if (carpooling != null && carpooling >= carpooling_min_km) {
            utils.log("rule \'all modes - update green points\': counting Carpooling green points");
            Double carpoolingDaily = $carpoolingTrips.getPeriodCurrentScore("daily");
            if (carpoolingDaily <= carpooling_daily_max) {
                if (isDriver && firstPair) {
                    score = score + driver_first_passenger_bonus;
                }
                if (isDriver && firstPair == false) {
                    score = score + driver_other_passenger_bonus;
                }
                if (isDriver == false) {
                    score = score + passenger_bonus;
                }
            } else {
                utils.log("rule \'all modes - update green points\': Reached daily limit for carpooling trips");
            }
        }
        if (bus != null) {
            utils.log("rule \'all modes - update green points\': counting Bus Km green points");
            double modeDaily = $busKm.getPeriodCurrentScore("daily");
            double gainedScore = tripScore(modeDaily, (double) bus, "Bus");
            utils.log("daily Km: " + modeDaily);
            score += gainedScore;
        }
        if (train != null) {
            utils.log("rule \'all modes - update green points\': counting Train Km green points");
            double modeDaily = $trainKm.getPeriodCurrentScore("daily");
            double gainedScore = tripScore(modeDaily, (double) train, "Train");
            utils.log("daily Km: " + modeDaily);
            score += gainedScore;
        }
        MessageNotification mn = new MessageNotification($gameId,$playerId,null);
        mn.addData("travelId", travelId);
        mn.addData("score", score);
        insert(mn);
        utils.log("calcultated score: " + score);
        if (score > 0.0) {
            $pc.setScore($pc.getScore() + score);
            update($pc);
        } else {
            utils.log("No score to update");
        }
end
